-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  listing_id uuid NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  reason text DEFAULT 'blocked'::text,
  booking_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT availability_pkey PRIMARY KEY (id),
  CONSTRAINT availability_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id),
  CONSTRAINT availability_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  listing_id uuid NOT NULL,
  renter_id uuid NOT NULL,
  host_id uuid NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  total_amount numeric NOT NULL,
  service_fee numeric NOT NULL,
  host_payout numeric NOT NULL,
  status text DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'payment_processing'::text, 'confirmed'::text, 'active'::text, 'completed'::text, 'cancelled'::text, 'disputed'::text])),
  vehicle_plate text,
  vehicle_type text,
  special_notes text,
  paymongo_link_url text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  price_per_unit numeric,
  duration_hours numeric,
  base_amount numeric,
  host_fee numeric,
  deposit_amount numeric DEFAULT 0,
  total_charge numeric,
  vehicle_color text,
  guest_count integer,
  paymongo_link_id text,
  paymongo_payment_id text,
  confirmed_at timestamp with time zone,
  activated_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id),
  CONSTRAINT bookings_renter_id_fkey FOREIGN KEY (renter_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.listing_equipment (
  listing_id uuid NOT NULL,
  equipment_type text,
  brand text,
  model text,
  condition text CHECK (condition = ANY (ARRAY['new'::text, 'excellent'::text, 'good'::text, 'fair'::text])),
  quantity integer DEFAULT 1,
  includes ARRAY,
  requires_deposit boolean DEFAULT true,
  damage_policy text,
  CONSTRAINT listing_equipment_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_equipment_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listing_meeting_rooms (
  listing_id uuid NOT NULL,
  room_type text CHECK (room_type = ANY (ARRAY['boardroom'::text, 'training_room'::text, 'hot_desk'::text, 'private_office'::text, 'open_space'::text])),
  total_area_sqm numeric,
  max_capacity integer DEFAULT 8,
  has_projector boolean DEFAULT false,
  has_whiteboard boolean DEFAULT false,
  has_wifi boolean DEFAULT false,
  has_coffee boolean DEFAULT false,
  has_printer boolean DEFAULT false,
  setup_types ARRAY DEFAULT '{}'::text[],
  amenities ARRAY DEFAULT '{}'::text[],
  CONSTRAINT listing_meeting_rooms_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_meeting_rooms_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listing_parking (
  listing_id uuid NOT NULL,
  space_type text CHECK (space_type = ANY (ARRAY['covered'::text, 'open'::text, 'underground'::text, 'garage'::text])),
  vehicle_types ARRAY DEFAULT '{}'::text[],
  total_area_sqm numeric,
  has_cctv boolean DEFAULT false,
  has_ev_charger boolean DEFAULT false,
  access_type text CHECK (access_type = ANY (ARRAY['key'::text, 'card'::text, 'gate_code'::text, 'open'::text])),
  floor_level text,
  CONSTRAINT listing_parking_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_parking_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listing_rooms (
  listing_id uuid NOT NULL,
  room_type text CHECK (room_type = ANY (ARRAY['private_room'::text, 'studio'::text, 'apartment'::text, 'house'::text, 'condo'::text, 'bed_space'::text])),
  total_area_sqm numeric,
  max_guests integer DEFAULT 1,
  bedrooms integer DEFAULT 1,
  bathrooms integer DEFAULT 1,
  has_aircon boolean DEFAULT false,
  has_wifi boolean DEFAULT false,
  has_kitchen boolean DEFAULT false,
  has_parking boolean DEFAULT false,
  furnished boolean DEFAULT true,
  check_in_time time without time zone DEFAULT '14:00:00'::time without time zone,
  check_out_time time without time zone DEFAULT '12:00:00'::time without time zone,
  CONSTRAINT listing_rooms_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_rooms_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listing_vehicles (
  listing_id uuid NOT NULL,
  vehicle_type text CHECK (vehicle_type = ANY (ARRAY['sedan'::text, 'suv'::text, 'van'::text, 'truck'::text, 'motorcycle'::text, 'bus'::text, 'other'::text])),
  make text,
  model text,
  year integer,
  color text,
  plate_number text,
  transmission text CHECK (transmission = ANY (ARRAY['automatic'::text, 'manual'::text])),
  fuel_type text CHECK (fuel_type = ANY (ARRAY['gasoline'::text, 'diesel'::text, 'electric'::text, 'hybrid'::text])),
  seats integer DEFAULT 5,
  with_driver boolean DEFAULT false,
  fuel_included boolean DEFAULT false,
  mileage_limit_km integer,
  insurance_included boolean DEFAULT false,
  CONSTRAINT listing_vehicles_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_vehicles_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listing_venues (
  listing_id uuid NOT NULL,
  venue_type text CHECK (venue_type = ANY (ARRAY['rooftop'::text, 'function_hall'::text, 'garden'::text, 'beach'::text, 'indoor'::text, 'outdoor'::text, 'other'::text])),
  total_area_sqm numeric,
  max_capacity integer,
  has_sound_system boolean DEFAULT false,
  has_projector boolean DEFAULT false,
  has_aircon boolean DEFAULT false,
  has_catering boolean DEFAULT false,
  has_parking boolean DEFAULT false,
  setup_types ARRAY DEFAULT '{}'::text[],
  min_hours integer DEFAULT 4,
  CONSTRAINT listing_venues_pkey PRIMARY KEY (listing_id),
  CONSTRAINT listing_venues_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  host_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['parking'::text, 'room'::text, 'vehicle'::text, 'equipment'::text, 'event_venue'::text, 'meeting_room'::text, 'storage'::text])),
  title text NOT NULL,
  description text,
  address text NOT NULL,
  city text NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  price numeric NOT NULL,
  price_unit text NOT NULL CHECK (price_unit = ANY (ARRAY['hour'::text, 'day'::text, 'week'::text, 'month'::text])),
  deposit numeric NOT NULL,
  instant_book boolean DEFAULT false,
  review_count integer DEFAULT 0,
  avg_rating numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'deleted'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tags ARRAY DEFAULT '{}'::text[],
  barangay text,
  min_booking_hours integer DEFAULT 1,
  max_booking_days integer DEFAULT 30,
  advance_notice_hours integer DEFAULT 1,
  buffer_hours integer DEFAULT 0,
  amenities ARRAY DEFAULT '{}'::text[],
  house_rules text,
  cancellation_policy text DEFAULT 'flexible'::text,
  cover_photo_url text,
  photos ARRAY DEFAULT '{}'::text[],
  total_bookings integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  CONSTRAINT listings_pkey PRIMARY KEY (id),
  CONSTRAINT listings_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  body text NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.profiles(id),
  CONSTRAINT messages_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  paymongo_event_type text NOT NULL,
  paymongo_resource_id text,
  amount numeric NOT NULL,
  currency text DEFAULT 'PHP'::text,
  status text NOT NULL,
  raw_payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  host_id uuid NOT NULL,
  amount numeric NOT NULL,
  status text DEFAULT 'pending'::text,
  payout_method text DEFAULT 'gcash'::text,
  payout_reference text,
  scheduled_for timestamp with time zone,
  paid_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payouts_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  avatar_url text,
  is_verified boolean DEFAULT false,
  gov_id_url text,
  expo_push_token text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bio text,
  default_lat double precision,
  default_lng double precision,
  default_city text DEFAULT 'Davao City'::text,
  id_verification_status text DEFAULT 'none'::text,
  gov_id_selfie_url text,
  total_listings integer DEFAULT 0,
  total_earnings numeric DEFAULT 0,
  host_rating numeric,
  host_review_count integer DEFAULT 0,
  total_bookings integer DEFAULT 0,
  renter_rating numeric,
  renter_review_count integer DEFAULT 0,
  is_host boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  listing_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  review_type text NOT NULL CHECK (review_type = ANY (ARRAY['renter_to_host'::text, 'host_to_renter'::text])),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  accuracy_rating integer CHECK (accuracy_rating >= 1 AND accuracy_rating <= 5),
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  value_rating integer CHECK (value_rating >= 1 AND value_rating <= 5),
  cleanliness_rating integer CHECK (cleanliness_rating >= 1 AND cleanliness_rating <= 5),
  comment text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.saved_listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  listing_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saved_listings_pkey PRIMARY KEY (id),
  CONSTRAINT saved_listings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT saved_listings_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);